export const fakeRooms = [
    {
        id: 12,
        title: 'Réception d\'habbo',
        description: 'ce qui colle au doigt c pas du réglisse',
        status: 'opened', // opened, knock-knock, password
        statusText: 'Ouvert',
        usersIn: 159,
        usersMax: 57,
        photo: 'https://swf.habbocity.me/c_images/navigator-thumbnail/1342840.png',
        owner: {
            username: 'Eklopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 2,
        title: 'lalalalal |♫efzjiozejofezjio',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 59,
        usersMax: 57,
        photo: 'https://swf.habbocity.me/c_images/navigator-thumbnail/1342840.png',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: false,
        canTroc: false,
    },
    {
        id: 3,
        title: 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
        description: 'feizjfioezjfoezj',
        status: 'knock-knock',
        statusText: 'Sonnette activée',
        usersIn: 54,
        usersMax: 57,
        photo: 'https://swf.habbocity.me/c_images/navigator-thumbnail/1342840.png',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: false,
        canTroc: false,
    },
    {
        id: 4,
        title: '|||||||||||||||||||||||||||||||||||||||||||||||',
        description: 'feizjfioezjfoezj',
        status: 'password',
        statusText: 'Mot de passe requis',
        usersIn: 30,
        usersMax: 57,
        photo: 'https://swf.habbocity.me/c_images/navigator-thumbnail/1342840.png',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: false,
        canTroc: false,
    },
    {
        id: 5,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: 'https://swf.habbocity.me/c_images/navigator-thumbnail/1342840.png',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: false,
        canTroc: false,
    },
    {
        id: 6,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: 'https://swf.habbocity.me/c_images/navigator-thumbnail/1342840.png',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: false,
        canTroc: false,
    },
    {
        id: 7,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 2,
        usersMax: 57,
        photo: 'https://swf.habbocity.me/c_images/navigator-thumbnail/1342840.png',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: false,
        canTroc: false,
    },
    {
        id: 8,
        title: '|||||||||||||||||||||||||||||||||||||||||||||||',
        description: 'feizjfioezjfoezj',
        status: 'password',
        statusText: 'Mot de passe requis',
        usersIn: 30,
        usersMax: 57,
        photo: 'https://swf.habbocity.me/c_images/navigator-thumbnail/1342840.png',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: false,
        canTroc: false,
    },
    {
        id: 9,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: false,
        canTroc: false,
    },
    {
        id: 10,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 11,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 2,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 12,
        title: '|||||||||||||||||||||||||||||||||||||||||||||||',
        description: 'feizjfioezjfoezj',
        status: 'password',
        statusText: 'Mot de passe requis',
        usersIn: 30,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 13,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 14,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 15,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 2,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 16,
        title: '|||||||||||||||||||||||||||||||||||||||||||||||',
        description: 'feizjfioezjfoezj',
        status: 'password',
        statusText: 'Mot de passe requis',
        usersIn: 30,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 17,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 18,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 19,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 2,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 20,
        title: '|||||||||||||||||||||||||||||||||||||||||||||||',
        description: 'feizjfioezjfoezj',
        status: 'password',
        statusText: 'Mot de passe requis',
        usersIn: 30,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 21,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 22,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 23,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 2,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 24,
        title: '|||||||||||||||||||||||||||||||||||||||||||||||',
        description: 'feizjfioezjfoezj',
        status: 'password',
        statusText: 'Mot de passe requis',
        usersIn: 30,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 25,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 26,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 27,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 2,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 28,
        title: '|||||||||||||||||||||||||||||||||||||||||||||||',
        description: 'feizjfioezjfoezj',
        status: 'password',
        statusText: 'Mot de passe requis',
        usersIn: 30,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 29,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 30,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 10,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
    {
        id: 31,
        title: 'lalalalal',
        description: 'feizjfioezjfoezj',
        status: 'opened',
        statusText: 'Ouvert',
        usersIn: 2,
        usersMax: 57,
        photo: '',
        owner: {
            username: 'Ekllopsis',
            look: '',
        },
        isGroupHQ: true,
        canTroc: true,
    },
];
