export interface IFurniData {
    floorItems: {
        [id: number]: {
            id: number,
            className: string,
            revision: number,
            category: string,
            defaultdir: number,
            xdim: number,
            ydim: number,
            partcolors: string[],
            name: string,
            description: string,
            adurl: string,
            offerid: number,
            buyout: number,
            rentofferid: number,
            rentbuyout: number,
            bc: number,
            excludeddynamic: boolean,
            customparams: string,
            specialtype: string,
            canstandon: boolean,
            cansiton: boolean,
            canlayon: boolean,
            furniline: string,
            environment: string,
            rare: boolean,
        }
    },
    wallItems: {
        [id: number]: {
            id: number,
            className: string,
            revision: number,
            name: string,
            description: string,
            adurl: number,
            offerid: number,
            buyout: number,
            rentofferid: number,
            rentbuyout: number,
            bc: number,
            excludeddynamic: boolean,
            specialtype: string,
            furniline: string,
            environment: string,
            rare: boolean,
        }
    }
}
